#!/bin/bash

# programmer >> yohana akhtari
# weblog >> mrtrojan.blog.ir
# aparat >> aparat.com/mrtrojan

tput clear
tput setaf  10

clear

python kindlylinux.py


tput cup 15 30

tput setaf 4

echo "Pow to Mr.Trojan ...."

echo "if your not root---->press Enter and type >> sudo su"

echo "programmer : yohana akhtari 'Mr.Trojan'"
echo "weblog : mrtrojan.blog.ir"
echo "aparat: http://aparat.com/mrtrojan"

tput sgr0

tput rev

tput sgr0 tput cup 7 15

tput bold
echo "press Enter for Quit"
echo ""
echo "(1) Solve the problems repository "
echo ""

read -p  "Enter Command >>> " input



if [ "$input" == "1" ];then
	echo "(1) ubutnu"
	echo "(2) kali" 
	echo "(3) backtrack"

	cd "/etc/apt/"

	#touch sources.list
	
	read -p "Enter number for os linux >>" oslinux
	
	if [ "$oslinux" == "1" ];then
		echo "#deb cdrom:[Ubuntu 18.04.1 LTS _Bionic Beaver_ - Release amd64 (20180725)]/ bionic main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic universe
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://us.archive.canonical.com/ubuntu bionic partner
# deb-src http://us.archive.canonical.com/ubuntu bionic partner

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
# deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse

deb http://ch.us.archive.ubuntu.com/ubuntu/ saucy main restricted

deb-src http://ch.archive.ubuntu.com/ubuntu/ saucy main restricted

deb http://us.archive.ubuntu.com/ubuntu/ saucy universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ saucy universe
deb http://us.archive.ubuntu.com/ubuntu/ saucy-updates multiverse universe
deb-src http://us.archive.ubuntu.com/ubuntu/ saucy-updates universe

# deb-src http://us.archive.ubuntu.com/ubuntu/ saucy universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ saucy-updates universe multiverse

deb http://archive.canonical.com/ubuntu saucy partner
deb-src http://archive.canonical.com/ubuntu saucy partner" > sources.list
	fi	
	if [ "$oslinux" == "2" ];then
		echo "deb http://http.kali.org/kali kali-rolling main non-free contrib
deb-src http://http.kali.org/kali kali-rolling main non-free contrib
deb http://http.kali.org/kali kali-rolling main non-free contrib" > sources.list
	fi
	if [ "$oslinux" == "3" ];then
		echo "deb http://all.repository.backtrack-linux.org revolution main microverse non-free testing .
deb http://32.repository.backtrack-linux.org revolution main microverse non-free testing .
deb http://64.repository.backtrack-linux.org revolution main microverse non-free testing .
deb http://source.repository.backtrack-linux.org revolution main microverse non-free testing" > sources.list
	fi
		
	apt-get clean
	apt-get update
	cd /var/lib/apt
	mv lists lists.old
	mkdir -p lists/partial
	apt-get update
	clear
	echo "now install sl app for testing repository"
	sleep 3
	apt install sl
fi
if [ "$input" == "" ];then
	exit
fi

